# site settings
title: Liberale M채nner
subtitle: 
email: info@liberale-maenner.at
description: Hiermit laden wir herzlich ein zur Gr체ndungsversammlung der Liberalen M채nner e.V. am Samstag, 5. August um 13-16 Uhr in N체rnberg.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Oliver P. Hoffmann
street_address: Karolinengasse 31/20
city: Wien
state: 
zip_code: 1040
country: Austria
phone: 
logo: "assets/images/logo.png" 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/liberalemaennerat
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/liberalemaenner

# build settings
markdown: kramdown

sass:
  style: compressed
